# Generated by Django 4.0.1 on 2022-01-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=10)),
                ('Last_Name', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=10)),
                ('Contacts', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
