# Generated by Django 4.0.1 on 2022-01-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(default='No', max_length=10, null=True),
        ),
    ]
